### PR TITLE
Add support for contineous integration - Circle CI

### PR DESCRIPTION
**Pull request by amardeshbd**
I added support for CI build using circle CI. It's free, need to signup for it and enable it for PkRSS using https://circleci.com/add-projects

If you don't want it, just close the PR.

Changelog
- Added circle CI config that does `assembleDebug` test (validates code compiles)
- Made `gradlew` to executable so that CI build can run it.

See CI in action - https://github.com/amardeshbd/PkRSS/pull/2 & https://circleci.com/gh/amardeshbd/PkRSS/4

### CODE REVIEW

**Comment by Pkmmte** [comment]
Interesting. I never really thought about supporting CI in this project but I'll look into it.

Just out of curiosity, what made you choose CircleCI over Travis CI?

**Comment by amardeshbd** [comment]
Personally I use both, I started with Travis, then used Circle. 
The UI for circle is much better. On the other hand, Travis has no limit. But, the allocation circle has should be more than enough for this project.

If you want, I can also do travis for you. You can have both, as both are free 😄 

I've started using this project, and have encountered few issues, was I though it would be better to have CI validating build passes for future PR.

**Comment by amardeshbd** [comment]
I'll try to do travis when I get 🏠

**Comment by amardeshbd** [comment]
Here is travis support https://travis-ci.org/amardeshbd/PkRSS/builds/174591767

screen shot 2016-11-09 at 3 43 43 pm

**Comment by Pkmmte** [comment]
Thanks! I'll definitely check this out once I get home and report back!

**Comment by Pkmmte** [comment]
Welp, so much for "once I get home".

Anyways, I finally had some time to check it. This was my first time working with CI (I usually code solo) so I didn't expect it to be so easy. Thanks!

**Pull request merged**
