### PR TITLE
[FIXED] OkHttp3 not supported exception.

### PR DESCRIPTION
**Pull request by amardeshbd**
Added logic to use existing OkHttp3 downloader implementation. 
Fixes https://github.com/Pkmmte/PkRSS/issues/31

### CODE REVIEW

**Comment by amardeshbd** [comment]
Good point @Pkmmte - in that case i don't think  we need to check for `Class.forName("com.squareup.okhttp.OkUrlFactory");`

We can start with default implementation.
```
Downloader downloaderInstance = new DefaultDownloader(context);
```
And remove anything related to `okUrlFactory`, I was not sure about `if (okHttpClient != okUrlFactory)`
The exception would occur, when one is available and other is not. Which is not ideal.

Let me know how would you want to change it.

**Comment by Pkmmte** [comment]
@amardeshbd I agree that we don't need to check for `OkUrlFactory`. When I wrote this part, it was just a copy and paste of a similar method in Square's Picasso library. 

I think an even better implementation would be to check for `null` in the last return statement in addition to removing anything related to `okUrlFactory` like you proposed. If not null, return the `downloaderInstance`, else return `new DefaultDownloader(context)`. That way, we're not creating a new `DefaultDownloader` instance if we aren't going to use it.

I'll merge this pull request after the changes are made. If you have a better solution than what I suggested, feel free to go with it! :)

**Comment by amardeshbd** [comment]
Yeah, sounds good. I have cleaned up code in https://github.com/Pkmmte/PkRSS/pull/33/commits/5bdde977a846fcc6f3580c0176f0f13cd69c8f45

**Comment by Pkmmte** [comment]
Thanks for the fix!

**Pull request merged**
