### PR TITLE
Implement media content parsing for RSS feeds

### PR DESCRIPTION
**Pull request by fusion44**
I've implemented media content parsing for RSS feeds. 

More info [here](http://www.rssboard.org/media-rss#media-content)

### CODE REVIEW

**Comment by Pkmmte** [comment]
Thanks for the pull request!

Before I merge, I have one question: why did you decide to use a Vector instead of a synchronized List?

**Comment by fusion44** [comment]
My pleasure. I didn't use it because I didn't know about it. Now that I've read a bit more about Vectors in Java I'll change the code to a synchronized list. Vectors seem to be more or less deprecated. 
Sorry about that.

**Comment by Pkmmte** [comment]
I'd appreciate it if you could modify your pull request to use a regular ArrayList instead. I don't think synchronization is really necessary for this. :)

**Comment by fusion44** [comment]
Sorry! It might take a few additional days to get this through. To much todo but not enough time :-) 
I'll do it next week at latest.

**Comment by Pkmmte** [comment]
I'll go ahead and merge it anyway. I'll take care of modifying it.

**Comment by fusion44** [comment]
Thank you and sorry.

**Pull request merged**
